FROM debian:latest

ARG POSTGRES_VERSION

RUN apt-get update \
 && apt-get install --yes \
   curl \
   git \
   unzip \
   wget \
   gnupg \
   jq \
   postgresql \
 && rm --recursive --force /var/lib/apt/lists/* \
 && addgroup --gid 986 jenkins \
 && adduser \
  --disabled-password \
  --ingroup jenkins \
  --uid 990 \
  --gecos "" jenkins \
 && curl --location https://aka.ms/InstallAzureCLIDeb | bash \
 && az aks install-cli
USER jenkins:jenkins